version: '3.7'
services:
  backend:
    image: node
    env_file: .env
    container_name: backend
    working_dir: /usr/app
    volumes:
      - .:/usr/app
    command: yarn dev
    ports:
      - "3333:3333"